source 'https://rubygems.org'

ruby '2.0.0'

gem 'rails', '3.2.14'
gem 'sqlite3'

# Gems used only for assets and not required
# in production environments by default.
group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
  gem 'bourbon', '~> 3.1.8'
  gem 'neat', '~> 1.5.0'
  gem 'angularjs-rails', '~> 1.2.1'
  gem 'angular-rails-templates'
  gem 'underscore-rails'
  gem 'd3-rails'
end

group :development, :test do
  gem 'rspec-rails', '~> 2.0'
  gem 'capybara'
  gem 'poltergeist'
  gem 'selenium-webdriver'
  gem 'factory_girl_rails'
  gem 'pry'
  gem 'rubocop'
  gem 'launchy'
  gem 'spring'
  gem 'spring-commands-rspec'
  gem 'database_cleaner'
  gem 'coffeelint'
  gem 'brakeman', require: false
  gem 'quiet_assets'
end

gem 'devise'

gem 'jquery-rails'
gem 'foreman'

# To use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# To use Jbuilder templates for JSON
# gem 'jbuilder'

# Use unicorn as the app server
# gem 'unicorn'

# Deploy with Capistrano
# gem 'capistrano'

# To use debugger
# gem 'debugger'
