#!/usr/bin/env rake

require File.expand_path('../config/application', __FILE__)

Albatross::Application.load_tasks

require 'rubocop/rake_task'
Rubocop::RakeTask.new

task(:default).clear
task default: [:spec, :rubocop, :coffeelint, :whitespace]

task ci: [:spec, :rubocop, :coffeelint, :whitespace]
